const actionTypes = {
  MODAL_WINDOW_TOGGLE: 'MODAL_WINDOW_TOGGLE',

  REMOVE_USER_BY_ID: 'REMOVE_USER_BY_ID',

  LOAD_USERS_LIST_REQUEST: 'LOAD_USERS_LIST_REQUEST',
  LOAD_USERS_LIST_SUCCESS: 'LOAD_USERS_LIST_SUCCESS',
  LOAD_USERS_LIST_FAILURE: 'LOAD_USERS_LIST_FAILURE',

  GET_CURRENT_USER_INFO_REQUEST: 'GET_CURRENT_USER_INFO_REQUEST',
  GET_CURRENT_USER_INFO_SUCCESS: 'GET_CURRENT_USER_INFO_SUCCESS',
  GET_CURRENT_USER_INFO_FAILURE: 'GET_CURRENT_USER_INFO_FAILURE'
};

export default actionTypes;
